### ISSUE TITLE
Change `Engine` generic type 

### ISSUE THREAD

**Issue by yuqi1129** [tikv/raft-engine#106]
In order to complete the issue [Update the version of raft-engine as it has out of date](https://github.com/tikv/tikv/issues/10986), 

Raft-engine can't export `Engine::open` method, see below 

**TiKV**
```rust
    pub fn new(config: RaftEngineConfig) -> Result<Self> {
        Ok(RaftLogEngine(
            RawRaftEngine::open(config).map_err(transfer_error)?,
        ))
    }
```
Raft-engine
```rust
pub type Engine<M, FileBuilder = file_builder::DefaultFileBuilder> = engine::Engine<M, FileBuilder>;

impl<M> Engine<M, DefaultFileBuilder, FilePipeLog<DefaultFileBuilder>>
where
    M: MessageExt,
{
    pub fn open(
        cfg: Config,
    ) -> Result<Engine<M, DefaultFileBuilder, FilePipeLog<DefaultFileBuilder>>> {
        Self::open_with_listeners(cfg, vec![])
    }
}
```

We need to change 
```rust
pub type Engine<M, FileBuilder = file_builder::DefaultFileBuilder> = engine::Engine<M, FileBuilder>;
```
to 
```rust
pub type Engine<M, FileBuilder = file_builder::DefaultFileBuilder, FilePipe = file_pipe_log::FilePipeLog<file_builder::DefaultFileBuilder>> = engine::Engine<M, FileBuilder, FilePipe>;
```

**Comment by tabokie** [comment]
Could you elaborate on why this is needed?
I have a PR that updates the raft engine, and it doesn't require exposing more generic parameters, (https://github.com/tikv/tikv/pull/10937/files#diff-2257f21328c8b6ff1fe766f2eb70c427fe7d9ac1552105707d8d96a888b5209f)

**Comment by yuqi1129** [comment]
@tabokie Sorry, I do not notice this PR, I have create [this issue](https://github.com/tikv/tikv/issues/10986) and try to make raft-engine is update-to-date in tikv, However, Currently raft-engine do not expose `open` method in `Engine`, So i create this issue. this seems to be redundant
