### ISSUE TITLE
Add public interface to query corrupted raft group id (and preferably last intact log index)

### ISSUE THREAD

**Issue by yuqi1129** [tikv/raft-engine#109]
This is a subtask of #99, this task only provide interface to query the corrupted raft group id and the corresponding index in raft-engine. i will open a new issue in tikv so that user can get this information by using tikv control utils

**Comment by yuqi1129** [comment]
@tabokie ,Thanks for your advice, However, i still have some questions.

1.   The log file format is  log_file_header + log_batch_header + ( region_id +  log_entry_info) * n,  file can be corrupted at any position. let at say log_file_header, log_batch_header or other position. For example, region_id is corrupted, we can't get the corrupt region id and thus unable to region id information.  how do we cope with this situation?
2. For a raft log file as following 
    ```
       region_1 + log_entry + region_2 + log_entry2 + region_3 + log_entry3
  ``` 
if file corrupted at region 1 and all the information after it can't be deseriallized.  just truncate it ? if we just truncate it, how do we know there is something wrong with region 2 and region 3 ?

**Comment by tabokie** [comment]
@yuqi1129
When an segment is corrupted, we can deduce its containing regions by checking the content before and after it. Say file N is corrupted, and file N-1 contains region A index K, file N+1 contains region A index J; then we know for sure that file N contains region A index (K, J).
The catch here is we can only deduce the region info if there are some undamaged files after the corruption. We have no way to find out region info if multiple files at the end are all corrupted. The best thing we could do is to truncate the tail completely.
To wrap up, I think there are two types of corruptions here (intermediate corruption, tail corruption), and we need separate calls to handle them.

**Comment by tabokie** [comment]
Done in #132 and #140
