### ISSUE TITLE
Add ctl tool for Raft Engine

### ISSUE THREAD

**Issue by tabokie** [tikv/raft-engine#144]
We need a ctl tool to do data administration work mentioned in #99.

Some subcommands I have in mind:
- Dump: dump out all operations in log files
  - `ctl dump --file /path/to/file [--raft id1,id2,id3]`
  - `ctl dump --path /path path [--raft id1,id2,id3]`
- Consistency check: check log files for logical errors
  - `ctl check --path /path`
- Truncate: unsafely truncate log entries in log files
  - `ctl truncate --path /path --mode front/back/all --queue append/rewrite/all [--raft id1,id2,id3]`
- Autofill: repair log entry holes by fill in empty message
  - `ctl autofill --path /path --queue append/rewrite/all [--raft id1,id2,id3]`\

We can use [structopt](https://docs.rs/structopt/0.3.25/structopt/) to build a skeleton for this tool, fill in implementation later.

**Comment by tabokie** [comment]
Closing this, the implementation of commands can be tracked in #99

**Comment by yuqi1129** [comment]
@tabokie ， Should we do not need to implement the subcommand `autofill `, I have noticed that you have deleted this logic in main.rs in `ctl` 
https://github.com/tikv/raft-engine/blob/e32e3e78604b7115621f543dea1231132abd8778/ctl/src/main.rs#L82-L89

**Comment by tabokie** [comment]
@yuqi1129 Yes, no need
