### ISSUE TITLE
Replace app builder with derive macros in stress tool

### ISSUE THREAD

**Issue by tabokie** [tikv/raft-engine#155]
Similar to [ctl](https://github.com/tikv/raft-engine/tree/master/ctl) tool, we can replace the use of clap with [structopt](https://docs.rs/structopt/0.3.25/structopt/) in [stress](https://github.com/tikv/raft-engine/tree/master/stress). It can greatly simplify the code.

**Comment by skyzh** [comment]
You can use clap-v3.0 beta, which is the same as structopt. We have refactored from structopt to clap-v3.0 in TiKV before.

**Comment by ztelur** [comment]
Hi, I want to do this work, plz assign it to me

**Comment by tabokie** [comment]
Thanks! /assign @ztelur

**Comment by ztelur** [comment]
should we use clap-v3.0 or structopt?

**Comment by tabokie** [comment]
clap is fine, you can update ctl to use clap too.
