### ISSUE TITLE
Question: Rewritten file can not be rewritten again?

### ISSUE THREAD

**Issue by Yriuns** [tikv/raft-engine#202]
I noticed that `raft-engine` has a interesting feature:
> During garbage collection, Raft Engine scans for these holes and compacts log files to free up storage space.

Through the code, it seems that, after these `*.raftlog` files are compacted(rewritten), they become `*.rewrite` files.
And there is no chance for they to become `*.raftlog` files again, which indicates that `*.rewrite` files can not be rewritten again?

**Comment by tabokie** [comment]
`*.rewrite` files are actually rewritten here:
https://github.com/tikv/raft-engine/blob/3d94cb5cf0492da4947546b0c2a0b083edbf9328/src/purge.rs#L77-L83

One difference is, all `*.rewrite` files are rewritten in one batch, so that we don't need to fight the file sequence number again.

**Comment by Yriuns** [comment]
> `*.rewrite` files are actually rewritten here:
> 
> https://github.com/tikv/raft-engine/blob/3d94cb5cf0492da4947546b0c2a0b083edbf9328/src/purge.rs#L77-L83
> 
> One difference is, all `*.rewrite` files are rewritten in one batch, so that we don't need to fight the file sequence number again.

Thank you for your reply! But I'm still confused.
It seems that the `purge_to` function just remove useless `*.rewrite` files.
My question is, when there are a lot of holes in `*.rewrite` files, will they be compacted again?

**Comment by tabokie** [comment]
Yes, when the garbage data in rewrite queue exceeds a threshold (`needs_rewrite_log_files` returns true), `rewrite_rewrite_queue` will be called. It reads out all active entries in rewrite queue and append them back to the rewrite queue. After that, old rewrite files will not be referenced by any memtable, and `purge_to` can delete them.

**Comment by Yriuns** [comment]
> Yes, when the garbage data in rewrite queue exceeds a threshold (`needs_rewrite_log_files` returns true), `rewrite_rewrite_queue` will be called. It reads out all active entries in rewrite queue and append them back to the rewrite queue. After that, old rewrite files will not be referenced by any memtable, and `purge_to` can delete them.

I get it. Thanks a lot!

**Comment by tabokie** [comment]
Cheers
