### ISSUE TITLE
Recycle log files

### ISSUE THREAD

**Issue by tabokie** [tikv/raft-engine#214]
File allocation incurs big overhead, as #100 showed. We could reduce that overhead by reusing old log files. But directly recycling is not secure, because old log items could resurface under certain condition. One way to overcome this is to consider file id when calculating checksum for each log batch.

**Comment by LykxSassinator** [comment]
I'll try to handle it.
To be continued.

**Comment by LykxSassinator** [comment]
As the related issues,  #224 and #249 , both are merged, can we close this issue now?
