### ISSUE TITLE
How to print variable in debugger

### ISSUE THREAD

**Issue by stupidstan** [tikv/raft-engine#236]
编译
RUSTFLAGS=-Cdebuginfo=1 cargo build --example append-compact-purge

调试
gdb --args  ./target/debug/examples/append-compact-purge
![image](https://user-images.githubusercontent.com/4676685/178127445-a62d2d7b-2ab5-4ed2-b5d4-67d16b0cb3d5.png)

tikv的方法是
https://github.com/tikv/tikv/pull/11949
在Cargo.toml里设置debug=true

**Comment by stupidstan** [comment]
改成RUSTFLAGS=-Cdebuginfo=2 cargo build --example append-compact-purge就可以了
![image](https://user-images.githubusercontent.com/4676685/178127966-820e82b4-2f1d-4650-81f8-a0c2acbcd605.png)

**Comment by tabokie** [comment]
Appear we have a solution. Might need to add it to documentation.

Closing this.
