### ISSUE TITLE
Support reading block based log format

### ISSUE THREAD

**Issue by tabokie** [tikv/raft-engine#246]
Decode log batch from fixed-sized blocks. See a detailed design in [RocksDB wiki](https://github.com/facebook/rocksdb/wiki/Write-Ahead-Log-File-Format).

The write flow can be implemented later. Read is of higher priority to keep it in the format version V2.

This is a funding work for #168.

**Comment by LykxSassinator** [comment]
Got it. The basic structure has been built, and I need to supply relevant uts for it.
