### ISSUE TITLE
Support secondary log directory

### ISSUE THREAD

**Issue by tabokie** [tikv/raft-engine#257]
It can be useful to configure raft engine on a separate (smaller) disk. And when that disk is full, we should provide a way for raft-engine to locate newly created log files on the main disk volume.

**Comment by LykxSassinator** [comment]
U mean that we need a new configuration such as `sub-dir` or `assist-dir` to store logs on different disk?

With this pre-requisite, the main dir, that is, the current configuration `dir`, is still used as the default main directory to store logs. Only if the main `dir` is ***FULL*** or not accessible, we will use the `assist-dir` or `sub-dir` to store the incoming logs.

Meanwhile, about the abnormal circumstance:
* `sub-dir` is `None` or belongs to the same volumn of disk, if the disk is full, the newly file creation should fail.
