### ISSUE TITLE
Physical lock file needs to be unlocked when `DualPipe` instance is dropped

### ISSUE THREAD

**Issue by v0y4g3r** [tikv/raft-engine#287]
# Problem
When building Pipes, a physical LOCK file is created in working directory and locked exclusively by current process.
https://github.com/tikv/raft-engine/blob/6a6fe3bd2e0a1ca0b4fc643800ddc93abe74cd87/src/file_pipe_log/pipe_builder.rs#L436
The lock file instance is then held by the `_dir_lock` field of `DualPipes`.

https://github.com/tikv/raft-engine/blob/b95dd014fa252d9cf43799a0ab6974cf766be9ec/src/file_pipe_log/pipe.rs#L482-L486

But when `DualPipes` instance is dropped, the dir lock is not released.

# Proposal

Implement `Drop` trait for `DualPipes` and unlock the dir lock in it, so that different `Engine` instance inside the same process can share the same working directory. This will be useful when writing integration tests covering data persistence and log recovery cases.

**Comment by tabokie** [comment]
I think it is the current behavior? I didn't verify but we have a lot of unit tests that reopen the engine in the same process.

**Comment by v0y4g3r** [comment]
Sorry, just found that has nothing to do with raft-engine itself. I'll close this issue.
