### ISSUE TITLE
aborted rewrite-rewrite causes data loss

### ISSUE THREAD

**Issue by tabokie** [tikv/raft-engine#288]
Say we have the data:
```
append: [11, 15]
rewrite: [1, 10]
```
When doing rewrite on the whole rewrite queue, it panicked. The old rewrite queue is not cleaned up and only partial output is written:
```
append: [11, 15]
rewrite: [1. 10] [1, 5]
```
After restart, only logs from `[11, 15]` will be recovered.

**Comment by BusyJay** [comment]
There are two phenomenons in my tests:
1. After restarted, one raft group lost data and the tikv panicked again.
2. After second panic, another group that was successfully started in 1 also became corrupted.

This issue can only explain 2, right?

**Comment by tabokie** [comment]
Yes. As long as there's an on-going `purge_expired_files` at the restart time, it's possible to lose some Raft logs in the front.
