### ISSUE TITLE
`swappy_allocator::tests::test_grow_regression` failed in new rust nightly

### ISSUE THREAD

**Issue by MichaelScofield** [tikv/raft-engine#324]
See the `cargo test` output [here](https://github.com/MichaelScofield/raft-engine/actions/runs/5566652964/jobs/10167926571?pr=2):

```txt
...
thread 'swappy_allocator::tests::test_grow_regression' panicked at 'assertion failed: `(left == right)`
  left: `(2, 1, 0, 0)`,
 right: `(3, 1, 0, 0)`', src/swappy_allocator.rs:624:9
...
```

I think it's because the swappy allocator's `shrink` method was not called.

After some digging into rust stdlib, I found that it's because [this PR](https://github.com/rust-lang/rust/commit/d24be14276bc5e52c6ab42d29ab2ed717b2b583c#diff-e2a4f36a3e53f497d9b6257c46f39ddcc9bad9285ef3e740959b67436ea22086R435) made a change recently that if the shrinking vector's capacity is zero, it skips the call to `shrink`.

@tabokie can you confirm that? If so, what do you think to fix it?

**Comment by tabokie** [comment]
Good catch! Replacing the `clear` with `truncate(1)` should fix it.
