### ISSUE TITLE
GroupCommit mechanism results in low throughput and inability to fully utilize hardware performance

### ISSUE THREAD

**Issue by guoxiangCN** [tikv/raft-engine#353]

**Comment by tabokie** [comment]
In the early stage of this project, `fsync` is performed outside the lock. It proves to be inefficient and causes excessive disk IOPS that harms every other I/O task in the system.

Later a proposal was brought up (https://github.com/tikv/raft-engine/issues/258) to parallelize writes in configurable shards. But for our use case (AWS cloud disk), the performance gain is negligible.

**Comment by guoxiangCN** [comment]
I found that some pingcap boys doing multi wall writing in the blog of Hackathon.  Where can I find the relevant codo~
