### ISSUE TITLE
Release Roadmap

### ISSUE THREAD

**Issue by slow-zhang** [tikv/raft-engine#68]
when will this repo be used in tikv? Is there some guide if I want to use it in self-build tikv.

**Comment by DengJin88** [comment]
Same question, Is there any plan to use raft-engine instead of using rocksdb to store logs?

**Comment by tabokie** [comment]
@slow-zhang @rpbear88 As an experimental feature, TiKV can already leverage raft-engine (controlled by [config](https://github.com/tikv/tikv/blob/8188bb845ef487d9e14f9194cf669c87d53d31bb/etc/config-template.toml#L871)). This feature is still too early to ship to production environment, but you are welcome to try it out in testing. We appreciate your feedback for that matter.
And indeed we are working on a plan to productionize this engine, hopefully in next few releases.

**Comment by hykych** [comment]
@tabokie from which version we can try this feature? v5.0.1? or in master branch?

**Comment by tabokie** [comment]
> @tabokie from which version we can try this feature? v5.0.1? or in master branch?

@hykych v5.0.0 forward
